name: Release

on:
  push:
    tags:
      - 'v*'
  # Manual run
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string
        description: 'Tag to release'

jobs:
  release:
    name: release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag || github.ref_name }}

      - uses: actions/setup-node@v4
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'

      - run: yarn install
      - run: npx auto-dist-tag --write

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
